### ISSUE TITLE
Blab on Thursday, Oct. 15 at 6:30PM (10:30AM for you)?

### ISSUE THREAD

**Issue by kpalana** [vegantriathlete/how-to-brand-your-website#10]
Shall we start setting this up? I apologize I have been quiet. My candle has been burning at both ends.

**Comment by vegantriathlete** [comment]
I have a call scheduled from 9:30 - 10:30. So, it would be good to give me a bit of breathing room. Let's call it 10:40. I'll set up the Blab and put the link here.

**Comment by vegantriathlete** [comment]
https://blab.im/marc-e-isaacson-coblaboration-vol02-issue02-marc-kristen-branding-raising-vegan-children

**Comment by kpalana** [comment]
Thanks! See you in a few...
